package JavaGarden;

import java.io.*;
import java.nio.file.Files;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.*;


public class GardenGUI extends javax.swing.JFrame {
    public ArrayList<Vasarlo> vevok = new ArrayList<Vasarlo>();
    public ArrayList<Noveny> novenyek = new ArrayList<Noveny>();
    public DecimalFormat forint = new DecimalFormat("###,### Ft");
    public DecimalFormat darab = new DecimalFormat("###,### db");
    
    public GardenGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelELADAS = new javax.swing.JPanel();
        lblFocim = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKeszlet_ea = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVasarlok_ea = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelVASARLOK = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMINTAADATOK = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVasarlok = new javax.swing.JTable();
        txtVEVOID = new javax.swing.JTextField();
        txtVEVONEV = new javax.swing.JTextField();
        txtVEVOEGYENLEG = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnUJVASARLO = new javax.swing.JButton();
        cmbKEDVEZMENY = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        btnVEVOMENTES = new javax.swing.JButton();
        btnVEVOMEGSEM = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtFizetes = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        panelKESZLET = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblKESZLET = new javax.swing.JTable();
        txtTeljesErtek = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnKESZLETMINTA = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnKeszletMentes = new javax.swing.JButton();
        panelSEGITSEG = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblKERTESZET = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelELADAS.setBackground(new java.awt.Color(255, 255, 204));
        panelELADAS.setEnabled(false);

        lblFocim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFocim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFocim.setText("Vásárlói kiszolgáló felület");
        lblFocim.setToolTipText("A kertészet megnevezése");

        tblKeszlet_ea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Megnevezés", "Készlet", "Egységár", "Érték"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKeszlet_ea.setRowHeight(24);
        tblKeszlet_ea.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblKeszlet_ea.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblKeszlet_ea);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Készlet:");

        tblVasarlok_ea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblVasarlok_ea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vevőkód", "Név", "Egyenleg", "Kedvezmény"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVasarlok_ea.setRowHeight(24);
        tblVasarlok_ea.setRowMargin(3);
        tblVasarlok_ea.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tblVasarlok_ea);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Vásárló kiválasztása:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Kosár:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setText("FIZETÉS");

        javax.swing.GroupLayout panelELADASLayout = new javax.swing.GroupLayout(panelELADAS);
        panelELADAS.setLayout(panelELADASLayout);
        panelELADASLayout.setHorizontalGroup(
            panelELADASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelELADASLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelELADASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFocim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelELADASLayout.createSequentialGroup()
                        .addGroup(panelELADASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(panelELADASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelELADASLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(364, 364, 364))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        panelELADASLayout.setVerticalGroup(
            panelELADASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelELADASLayout.createSequentialGroup()
                .addComponent(lblFocim, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelELADASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelELADASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelELADASLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelELADASLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Eladás", panelELADAS);

        panelVASARLOK.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Vásárlók:");

        btnMINTAADATOK.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnMINTAADATOK.setText("Mintaadatok");
        btnMINTAADATOK.setToolTipText("Betölt néhány mintaadatot. Ha van már adat a listán, akkor kérdez.");
        btnMINTAADATOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMINTAADATOKMouseClicked(evt);
            }
        });
        btnMINTAADATOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMINTAADATOKActionPerformed(evt);
            }
        });

        tblVasarlok.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblVasarlok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vevőkód", "Név", "Egyenleg", "Kedvezmény"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVasarlok.setToolTipText("A vásárlók adatai");
        tblVasarlok.setRowHeight(24);
        tblVasarlok.setRowMargin(3);
        tblVasarlok.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblVasarlok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVasarlokMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVasarlok);

        txtVEVOID.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        txtVEVOID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtVEVOID.setToolTipText("A vásárló egyedi azonosítója");
        txtVEVOID.setEnabled(false);

        txtVEVONEV.setToolTipText("A vásárló neve. Kötelező kitölteni.");
        txtVEVONEV.setEnabled(false);

        txtVEVOEGYENLEG.setText("10000");
        txtVEVOEGYENLEG.setToolTipText("A vásárló kezdő egyenlege. Ha nem tölti ki, akkor automatikusan 10.000,- Ft lesz.");
        txtVEVOEGYENLEG.setEnabled(false);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setLabelFor(txtVEVOID);
        jLabel11.setText("Azonosító:");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setLabelFor(txtVEVONEV);
        jLabel12.setText("Név:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setLabelFor(txtVEVOEGYENLEG);
        jLabel13.setText("Egyenleg:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setLabelFor(cmbKEDVEZMENY);
        jLabel14.setText("Kedvezmény:");

        btnUJVASARLO.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnUJVASARLO.setText("Új vásárló");
        btnUJVASARLO.setToolTipText("Új vásárlóadat felvitele.");
        btnUJVASARLO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUJVASARLOMouseClicked(evt);
            }
        });
        btnUJVASARLO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUJVASARLOActionPerformed(evt);
            }
        });

        cmbKEDVEZMENY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "25" }));
        cmbKEDVEZMENY.setToolTipText("Állítsa be, hogy a vásárló mekkora mértékű kedvezményre jogosult.");
        cmbKEDVEZMENY.setEnabled(false);
        cmbKEDVEZMENY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKEDVEZMENYActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Vásárlók adatai");

        btnVEVOMENTES.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnVEVOMENTES.setText("MENTÉS");
        btnVEVOMENTES.setToolTipText("A vásárló adatainak mentése.");
        btnVEVOMENTES.setEnabled(false);
        btnVEVOMENTES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVEVOMENTESMouseClicked(evt);
            }
        });
        btnVEVOMENTES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVEVOMENTESActionPerformed(evt);
            }
        });

        btnVEVOMEGSEM.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnVEVOMEGSEM.setText("MÉGSEM");
        btnVEVOMEGSEM.setToolTipText("Kilépés a vásárló adatainak felviteléből mentés nélkül.");
        btnVEVOMEGSEM.setEnabled(false);
        btnVEVOMEGSEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVEVOMEGSEMActionPerformed(evt);
            }
        });

        jLabel22.setText("Fizetés:");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtFizetes.setToolTipText("A fizetés összege");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton2.setText("FIZETÉS");
        jButton2.setToolTipText("A beállított fizeési összeg érvényesítése");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVASARLOKLayout = new javax.swing.GroupLayout(panelVASARLOK);
        panelVASARLOK.setLayout(panelVASARLOKLayout);
        panelVASARLOKLayout.setHorizontalGroup(
            panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVASARLOKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVASARLOKLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelVASARLOKLayout.createSequentialGroup()
                        .addGroup(panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVASARLOKLayout.createSequentialGroup()
                                .addGroup(panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelVASARLOKLayout.createSequentialGroup()
                                        .addComponent(btnMINTAADATOK)
                                        .addGap(269, 269, 269)
                                        .addComponent(btnUJVASARLO, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVEVONEV, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVEVOID, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVEVOEGYENLEG, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbKEDVEZMENY, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelVASARLOKLayout.createSequentialGroup()
                                        .addGroup(panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtFizetes, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnVEVOMENTES, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnVEVOMEGSEM)
                                            .addComponent(jButton2)))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 89, Short.MAX_VALUE))))
        );
        panelVASARLOKLayout.setVerticalGroup(
            panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVASARLOKLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVASARLOKLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtVEVOID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVEVONEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVEVOEGYENLEG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbKEDVEZMENY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVEVOMENTES)
                            .addComponent(btnVEVOMEGSEM))
                        .addGap(21, 21, 21)
                        .addGroup(panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFizetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVASARLOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMINTAADATOK)
                    .addComponent(btnUJVASARLO))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vásárlók", panelVASARLOK);

        panelKESZLET.setBackground(new java.awt.Color(204, 255, 204));
        panelKESZLET.setEnabled(false);

        tblKESZLET.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Megnevezés", "Készlet", "Egységár", "Érték"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKESZLET.setRowHeight(24);
        tblKESZLET.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblKESZLET.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(tblKESZLET);

        txtTeljesErtek.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTeljesErtek.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Teljes érték:");

        btnKESZLETMINTA.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnKESZLETMINTA.setText("MINTAADATOK");
        btnKESZLETMINTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKESZLETMINTAActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Készlet adatok");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Készlet adatai:");

        btnKeszletMentes.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnKeszletMentes.setText("MENTÉS");
        btnKeszletMentes.setToolTipText("Lementi a készlet adatokat.");
        btnKeszletMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeszletMentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKESZLETLayout = new javax.swing.GroupLayout(panelKESZLET);
        panelKESZLET.setLayout(panelKESZLETLayout);
        panelKESZLETLayout.setHorizontalGroup(
            panelKESZLETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKESZLETLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKESZLETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelKESZLETLayout.createSequentialGroup()
                        .addComponent(btnKESZLETMINTA)
                        .addGap(248, 248, 248)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelKESZLETLayout.createSequentialGroup()
                        .addGroup(panelKESZLETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelKESZLETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelKESZLETLayout.createSequentialGroup()
                                    .addGap(125, 125, 125)
                                    .addComponent(btnKeszletMentes, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTeljesErtek, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 301, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelKESZLETLayout.setVerticalGroup(
            panelKESZLETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKESZLETLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelKESZLETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTeljesErtek, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addComponent(btnKESZLETMINTA)
                    .addComponent(btnKeszletMentes))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Készlet", panelKESZLET);

        panelSEGITSEG.setBackground(new java.awt.Color(204, 255, 204));
        panelSEGITSEG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Müller György");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("M66MZ0");

        jLabel4.setText("Elektronikus levélcím:");

        jLabel5.setText("Név:");

        jLabel6.setText("Neptun-kód:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("g.muller71@gmail.com");

        jLabel16.setText("Telefonszám:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("+36 (70) 310-4015");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Technikai segítség");

        javax.swing.GroupLayout panelSEGITSEGLayout = new javax.swing.GroupLayout(panelSEGITSEG);
        panelSEGITSEG.setLayout(panelSEGITSEGLayout);
        panelSEGITSEGLayout.setHorizontalGroup(
            panelSEGITSEGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSEGITSEGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSEGITSEGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSEGITSEGLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelSEGITSEGLayout.createSequentialGroup()
                        .addGroup(panelSEGITSEGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(panelSEGITSEGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSEGITSEGLayout.createSequentialGroup()
                                .addGroup(panelSEGITSEGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                                .addContainerGap(341, Short.MAX_VALUE))
                            .addGroup(panelSEGITSEGLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        panelSEGITSEGLayout.setVerticalGroup(
            panelSEGITSEGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSEGITSEGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(panelSEGITSEGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSEGITSEGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSEGITSEGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSEGITSEGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Technikai segítség", panelSEGITSEG);

        lblKERTESZET.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblKERTESZET.setForeground(new java.awt.Color(51, 153, 0));
        lblKERTESZET.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKERTESZET.setText("... kertészet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKERTESZET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblKERTESZET, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            File f = new File(JavaGarden.adatmappa + JavaGarden.kerteszetfile);
            if (f.exists() && !f.isDirectory()) {
                Scanner olvaso = new Scanner(f);
                String kerteszetneve = olvaso.nextLine();
                this.setTitle(kerteszetneve + " Kertészet");
                this.lblKERTESZET.setText(kerteszetneve + " Kertészet");
                olvaso.close();
            } else {
                this.lblFocim.setText("Nem találtam a kertészet nevét!");
            }
            
        } catch (FileNotFoundException e) {
            System.out.println("Hiba a kertészet adatainak beolvasása során!");
        }
        
        //*** Esetleges készletadatok beolvasása ***
        File fKeszlet = new File(JavaGarden.adatmappa + JavaGarden.keszletfile);
        if (fKeszlet.exists()) {
            //*** Van készletfile - beolvasás ***
            KeszletBeolvasas(fKeszlet);
            KeszletKiir();
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnMINTAADATOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMINTAADATOKMouseClicked
    }//GEN-LAST:event_btnMINTAADATOKMouseClicked

    private void btnMINTAADATOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMINTAADATOKActionPerformed
        int valasz = JOptionPane.YES_OPTION;
        if (vevok.size() > 0) {
            valasz = JOptionPane.showConfirmDialog(null, "A mintaadatok törlik az eddigi adatokat. Folytatja?", "MEGERŐSÍTÉS", JOptionPane.YES_NO_OPTION);
        }
        if (valasz == JOptionPane.YES_OPTION) {
            //*** VEVŐADATOK törlése ***
            vevok.removeAll(vevok);
            //*** MINTAADATOK ***
            vevok.add(new Vasarlo(1,"Első István",10000,0));
            vevok.add(new Vasarlo(2,"Második Béla",22000,25));
            vevok.add(new Vasarlo(3,"Harmadik Richárd",5000,25));
            vevok.add(new Vasarlo(4,"Negyedik Henrik",3200,0));
            vevok.add(new Vasarlo(5,"Ötödik Lajos",100,25));        

            //*** Vevők adatainak frissítése ***
            VevoAdatKiir();
        }
    }//GEN-LAST:event_btnMINTAADATOKActionPerformed

    private void cmbKEDVEZMENYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKEDVEZMENYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKEDVEZMENYActionPerformed

    private void btnUJVASARLOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUJVASARLOMouseClicked
        
    }//GEN-LAST:event_btnUJVASARLOMouseClicked

    private void btnVEVOMENTESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVEVOMENTESMouseClicked

    }//GEN-LAST:event_btnVEVOMENTESMouseClicked

    private void btnUJVASARLOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUJVASARLOActionPerformed
        this.txtVEVOID.setText(Integer.toString(vevok.size() + 1));
        VevoMezoEngedely(false);
    }//GEN-LAST:event_btnUJVASARLOActionPerformed

    private void btnVEVOMENTESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVEVOMENTESActionPerformed
        int valasz;
        Boolean rendben = true;
        valasz = JOptionPane.showConfirmDialog(null, "Elmenti az új vásárló adatait?","ADATMENTÉS", JOptionPane.YES_NO_OPTION);
        if (valasz == JOptionPane.YES_OPTION) {
            //*** Adatellenőrzés ***
            //*** Ki van-e töltve a név? ***
            if (this.txtVEVONEV.getText().isEmpty()) {
                rendben = false;
                JOptionPane.showMessageDialog(null, "Kérem adja meg a vásárló nevét!", "ADATHIBA !",JOptionPane.OK_OPTION);
            }
            ///*** Ha nem adták meg/kitörölték a kezdőegyenleget, akkor 10000 ***
            if (this.txtVEVOEGYENLEG.getText().isEmpty()) {
                this.txtVEVOEGYENLEG.setText("10000");
            }
            
            //*** Ha valami nem rontotta el, akkor mentés ***
            if (rendben) {
                int id = Integer.parseInt(this.txtVEVOID.getText());
                String nev = this.txtVEVONEV.getText();
                int egyenleg =Integer.parseInt(this.txtVEVOEGYENLEG.getText());
                int kedvezmeny = Integer.parseInt(this.cmbKEDVEZMENY.getSelectedItem().toString());
                vevok.add(new Vasarlo(id, nev, egyenleg, kedvezmeny));
                VevoAdatKiir();

                VevoMezoEngedely(true);
            }
        }
    }//GEN-LAST:event_btnVEVOMENTESActionPerformed

    private void btnVEVOMEGSEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVEVOMEGSEMActionPerformed
        int valasz = JOptionPane.showConfirmDialog(null, 
                "Valóban kilép az adatok mentése nélkül?", "FIGYELEM",
                JOptionPane.YES_NO_OPTION);
        if (valasz == JOptionPane.YES_OPTION) {
            this.txtVEVOID.setText(null);
            this.txtVEVONEV.setText(null);
            this.txtVEVOEGYENLEG.setText(null);
            
            VevoMezoEngedely(true);
        }
    }//GEN-LAST:event_btnVEVOMEGSEMActionPerformed

    private void tblVasarlokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVasarlokMouseClicked
        int index = this.tblVasarlok.getSelectedRow();
        this.txtVEVOID.setText(Integer.toString(vevok.get(index).id));
        this.txtVEVONEV.setText(vevok.get(index).nev);
        this.txtVEVOEGYENLEG.setText(Integer.toString(vevok.get(index).egyenleg));
        this.cmbKEDVEZMENY.setSelectedItem(Integer.toString(vevok.get(index).kedvezmeny));
    }//GEN-LAST:event_tblVasarlokMouseClicked

    private void btnKESZLETMINTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKESZLETMINTAActionPerformed
        int valasz = JOptionPane.YES_OPTION;
        if (novenyek.size() > 0) {
            valasz = JOptionPane.showConfirmDialog(null, 
                    "A mintaadatok törlik az eddigi adatokat. Folytatja?", "MEGERŐSÍTÉS", 
                    JOptionPane.YES_NO_OPTION);
        }
        if (valasz == JOptionPane.YES_OPTION) {
            //*** KÉSZLET ADATOK törlése ***
            novenyek.removeAll(novenyek);
            
            //*** MINTAADATOK ***
            novenyek.add(new Noveny(1,"Muskátli",12,990));
            novenyek.add(new Noveny(2,"Rózsa",32,1090));
            novenyek.add(new Noveny(3,"Tulipán",154,1990));
            novenyek.add(new Noveny(4,"Ibolya",55,490));
            novenyek.add(new Noveny(5,"Krizantém",48,890));
            novenyek.add(new Noveny(7,"Magnólia",4,3990));
            novenyek.add(new Noveny(8,"Magyar kajszibarack",8,3990));
            novenyek.add(new Noveny(9,"Alexander körte",6,3490));
            novenyek.add(new Noveny(10,"Hóvirág",78,490));

            Collections.sort(novenyek, Noveny.ArKomparator());

            //*** Készletadatok frissítése ***
            KeszletKiir();
        }
    }//GEN-LAST:event_btnKESZLETMINTAActionPerformed

    private void btnKeszletMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeszletMentesActionPerformed
        int valasz;
        valasz = JOptionPane.showConfirmDialog(null, "Valóban lementi a készletadatokat?", "ADATMENTÉS", JOptionPane.YES_NO_OPTION);
        if (valasz == JOptionPane.YES_OPTION) {
            File f = new File(JavaGarden.adatmappa + JavaGarden.keszletfile);
            
            if (f.exists()){
                //*** Van ilyen file ***
            } else {
                //*** Nincs ilyen nevű file ***
                KeszletKiiras(f);
            }
        }
    }//GEN-LAST:event_btnKeszletMentesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!this.txtVEVOID.getText().isEmpty()) {
            if (this.txtFizetes.getText().isEmpty()) {
                //*** Nem adott meg összeget ***
                JOptionPane.showMessageDialog(null,"Adja meg a fizetés összegét!", "ADATHIBA", JOptionPane.OK_OPTION);
            } else {

                try {
                    int osszeg = Integer.valueOf(this.txtFizetes.getText());
                    if (osszeg > 0) {
                        int id = Integer.parseInt(this.txtVEVOID.getText());
                        vevok.get(id-1).setEgyenleg(vevok.get(id-1).getEgyenleg() + osszeg);
                        VevoAdatKiir();
                    }
                } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(null, "Nem megfelelő az összeg!", "ADATHIBA", JOptionPane.OK_OPTION);
                }
                this.txtFizetes.setText(null);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Jelölje ki a vásárlót!", "KIJELÖLÉS", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GardenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GardenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GardenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GardenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GardenGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKESZLETMINTA;
    private javax.swing.JButton btnKeszletMentes;
    private javax.swing.JButton btnMINTAADATOK;
    private javax.swing.JButton btnUJVASARLO;
    private javax.swing.JButton btnVEVOMEGSEM;
    private javax.swing.JButton btnVEVOMENTES;
    private javax.swing.JComboBox<String> cmbKEDVEZMENY;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblFocim;
    private javax.swing.JLabel lblKERTESZET;
    private javax.swing.JPanel panelELADAS;
    private javax.swing.JPanel panelKESZLET;
    private javax.swing.JPanel panelSEGITSEG;
    private javax.swing.JPanel panelVASARLOK;
    private javax.swing.JTable tblKESZLET;
    private javax.swing.JTable tblKeszlet_ea;
    private javax.swing.JTable tblVasarlok;
    private javax.swing.JTable tblVasarlok_ea;
    private javax.swing.JTextField txtFizetes;
    private javax.swing.JTextField txtTeljesErtek;
    private javax.swing.JTextField txtVEVOEGYENLEG;
    private javax.swing.JTextField txtVEVOID;
    private javax.swing.JTextField txtVEVONEV;
    // End of variables declaration//GEN-END:variables

    public void VevoAdatKiir () {
        //*** Vevők adatainak frissítése ***
        DefaultTableModel dt1 = (DefaultTableModel) tblVasarlok.getModel();
        DefaultTableModel dt2 = (DefaultTableModel) tblVasarlok_ea.getModel();

        //*** Az előző adatok törlése MINDKÉT vevőlistáról***
        for(int i = dt1.getRowCount()-1;i>=0; i--) {
            dt1.removeRow(i);
        }   
        for(int i = dt2.getRowCount()-1;i>=0; i--) {
            dt2.removeRow(i);
        }   
        tblVasarlok.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblVasarlok.getColumnModel().getColumn(0).setPreferredWidth(80);
        tblVasarlok.getColumnModel().getColumn(1).setPreferredWidth(220);
        tblVasarlok.getColumnModel().getColumn(2).setPreferredWidth(80);
        tblVasarlok.getColumnModel().getColumn(3).setPreferredWidth(80);
        
        for (int i = 0; i < vevok.size(); i++) {
            Object[] sor = new Object[4];
            sor[0] = vevok.get(i).id;
            sor[1] = vevok.get(i).nev;
            sor[2] = forint.format(vevok.get(i).egyenleg);
            sor[3] = vevok.get(i).kedvezmeny;
            dt1.addRow(sor);
            dt2.addRow(sor);
        }
    }
    
    public void VevoMezoEngedely(Boolean eng) {
        this.tblVasarlok.setEnabled(eng);
        this.btnMINTAADATOK.setEnabled(eng);
        this.btnUJVASARLO.setEnabled(eng);
        this.panelELADAS.setEnabled(eng);
        this.panelKESZLET.setEnabled(eng);
        this.panelSEGITSEG.setEnabled(eng);

        this.txtVEVONEV.setEnabled(!eng);
        this.txtVEVOEGYENLEG.setEnabled(!eng);
        this.cmbKEDVEZMENY.setEnabled(!eng);
        this.btnVEVOMENTES.setEnabled(!eng);
        this.btnVEVOMEGSEM.setEnabled(!eng);
    }
    
    public void KeszletKiir() {
        //*** Készletadatok frissítése ***
        DefaultTableModel dt1 = (DefaultTableModel) tblKESZLET.getModel();
        DefaultTableModel dt2 = (DefaultTableModel) tblKeszlet_ea.getModel();

        //*** Az előző adatok törlése MINDKÉT készletlistáról ***
        for(int i = dt1.getRowCount()-1;i>=0; i--) {
            dt1.removeRow(i);
        }   
        for(int i = dt2.getRowCount()-1;i>=0; i--) {
            dt2.removeRow(i);
        }
        tblKESZLET.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblKESZLET.getColumnModel().getColumn(0).setPreferredWidth(252);
        tblKESZLET.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblKESZLET.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblKESZLET.getColumnModel().getColumn(3).setPreferredWidth(100);
        /*tblVasarlok.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblVasarlok.getColumnModel().getColumn(0).setPreferredWidth(80);
        tblVasarlok.getColumnModel().getColumn(1).setPreferredWidth(220);
        tblVasarlok.getColumnModel().getColumn(2).setPreferredWidth(80);
        tblVasarlok.getColumnModel().getColumn(3).setPreferredWidth(80);*/
        int teljesErtek = 0;
        
        for (int i = 0; i < novenyek.size(); i++) {
            Object[] sor = new Object[4];
            sor[0] = novenyek.get(i).getMegnevezes();
            sor[1] = darab.format(novenyek.get(i).getKeszlet());
            sor[2] = forint.format(novenyek.get(i).getEgysegar());
            sor[3] = forint.format(novenyek.get(i).getKeszlet() * novenyek.get(i).getEgysegar());
            teljesErtek += novenyek.get(i).getKeszlet() * novenyek.get(i).getEgysegar();
            dt1.addRow(sor);
            dt2.addRow(sor);
        }
        this.txtTeljesErtek.setText(forint.format(teljesErtek));
    }
    
    public void KeszletKiiras(File f) {
        try {
            FileWriter fw = new FileWriter(f);
            for (int i=0; i<novenyek.size(); i++){
                fw.write(novenyek.get(i).getId() + ";" + 
                         novenyek.get(i).getMegnevezes() + ";" +
                         novenyek.get(i).getKeszlet() + ";" +
                         novenyek.get(i).getEgysegar() + System.lineSeparator());
            }
            fw.close();
        } catch (IOException e) {
            System.err.println("Nem sikerült a file-ba írás!");
        }
    }
    
    public void KeszletBeolvasas(File f) {
        String sor;
        try {
            Scanner s = new Scanner(f);
            while (s.hasNext()) {
                sor=s.nextLine();
                String[] adat = sor.split(";");
                int id = Integer.parseInt(adat[0]);
                String megnevezes = adat[1];
                int keszlet = Integer.parseInt(adat[2]);
                int egysegar = Integer.parseInt(adat[3]);
                novenyek.add(new Noveny(id, megnevezes, keszlet, egysegar));
            }
            s.close();
        } catch (IOException e) {
            System.err.println("Nem sikerült a készletfile-t olvasni!");
        }
    }
            
}


