package JavaGarden;

import java.io.*;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.*;


public class GardenGUI extends javax.swing.JFrame {
    
    private ArrayList<Vasarlo> vevok;
    
    public GardenGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFocim = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnMINTAADATOK = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVasarlok = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblFocim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFocim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFocim.setText("Vásárlói kiszolgáló felület");
        lblFocim.setToolTipText("A kertészet megnevezése");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Vásárló kiválasztása:");

        btnMINTAADATOK.setText("Mintaadatok");
        btnMINTAADATOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMINTAADATOKMouseClicked(evt);
            }
        });

        tblVasarlok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Azonosító", "Név", "Egyenleg", "Kedvezmény"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVasarlok.setRowHeight(24);
        tblVasarlok.setRowMargin(3);
        jScrollPane2.setViewportView(tblVasarlok);
        if (tblVasarlok.getColumnModel().getColumnCount() > 0) {
            tblVasarlok.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFocim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMINTAADATOK)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFocim, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMINTAADATOK)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            File f = new File(JavaGarden.adatmappa + JavaGarden.kerteszetfile);
            if (f.exists() && !f.isDirectory()) {
                Scanner olvaso = new Scanner(f);
                //while (olvaso.hasNextLine()) {
                    String kerteszetneve = olvaso.nextLine();
                    //this.lblKerteszetID.setText("(" + adatok[0] + ")");
                    //this.lblMegnevezes.setText(adatok[1]);
                    this.setTitle(kerteszetneve);
                //}
                olvaso.close();
            } else {
                this.lblFocim.setText("Nem találtam a kertészet nevét!");
            }
            
        } catch (FileNotFoundException e) {
            System.out.println("Hiba a kertészet adatainak beolvasása során!");
        }
         
         
    }//GEN-LAST:event_formWindowOpened

    private void btnMINTAADATOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMINTAADATOKMouseClicked
        //Object adatok[][] = {{1,"Első Vásárló", 10000, 0},{2, "Második Vásárló", 22000, 25},{3, "Harmadik Vásárló", 5000, 25}};
        Vector v1 = new Vector();
        Vector v2 = new Vector();
        Vector v3 = new Vector();
        DefaultTableModel dt = (DefaultTableModel) tblVasarlok.getModel();
        
        //*** Az előző adatok törlése ***
        for(int i = dt.getRowCount()-1;i>=0; i--) {
            dt.removeRow(i);
        }
        v1.add(1);
        v1.add("Első Vásárló");
        v1.add(10000);
        v1.add(0);
        dt.addRow(v1);

        v2.add(2);
        v2.add("Második Vásárló");
        v2.add(22000);
        v2.add(25);
        dt.addRow(v2);

        v3.add(3);
        v3.add("Harmadik Vásárló");
        v3.add(5000);
        v3.add(25);
        dt.addRow(v3);
    }//GEN-LAST:event_btnMINTAADATOKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GardenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GardenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GardenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GardenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GardenGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMINTAADATOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFocim;
    private javax.swing.JTable tblVasarlok;
    // End of variables declaration//GEN-END:variables
}
